'use strict';

// tests for postSlack
// Generated by serverless-mocha-plugin

const mod = require('../postSlack/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('sns2slack', function() {
  this.timeout(10000);
  it('Send a message to a group', function(done) {
    wrapped.run({ Records: [ 
      { Sns: 
        { 
          Message: JSON.stringify({
            channel: '#sns2slack',
            message: 'Test Message',
            senderName: 'sns2slack tests'
          }) 
        }
      }
    ]}).then((response) => {
      console.log(response);
      done();
    }, (error) => {
      return done(error);
    });
  });
});
